name: flutter_playground
description: flutter playground

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
  fonts:
   - family: SAir
     fonts:
       - asset: fonts/SAir.ttf
   - family: SBold
     fonts:
       - asset: fonts/SBold.ttf